### ISSUE TITLE
Making init easier

### ISSUE THREAD

**Issue by LeaVerou** [valterkraemer/mavo-firebase#2]
Currently your readme expects that users understand the code that Firebase gives them and can parse out the details that this backend needs. This is probably a fair assumption for many, but not all Mavo users, and even for those who can read it, it's a hassle to be copying values separately.

It would be both easier and faster (and this is what we did with @lizzie's Firebase backend) if they could just copy/paste the code required and the backend would just figure it out.

What do you think?

**Comment by valterkraemer** [comment]
I actually had it like that earlier. But changed it mainly because I wanted to be able to setup without any JavaScript at all.

One benefit of having it as an attribute is that you can have multiple firebase databases on the same page.

...And that the `mv-storage` attribute looks really clean :)

**Comment by LeaVerou** [comment]
We went the opposite way: we had attributes first, then we wondered: isn't the whole point of using HTML to make things easier? In this case, Firebase is **already** giving people the `<script>`, so asking them to extract the keys etc is *more* work, and requires *more* knowledge.
You’re right about the multiple databases though, we made the compromise of only having one.

What about supporting both? Then you get the best of both worlds :)

**Comment by valterkraemer** [comment]
> What about supporting both? Then you get the best of both worlds :)

Yeah, that's probably the way to go.

**Comment by LeaVerou** [comment]
Then you could have two sections in the readme: Quick setup and Advanced setup :)

**Comment by valterkraemer** [comment]
Now supports both ways.
