### ISSUE TITLE
Broken high score demo?

### ISSUE THREAD

**Issue by LeaVerou** [valterkraemer/mavo-firebase#5]
I get this error when trying to login:

![image](https://user-images.githubusercontent.com/175836/33747413-da73efa8-db90-11e7-9107-6f6cc639f051.png)

Btw why use `?login`? It's a demo, so having a button would be perfectly acceptable…

**Comment by valterkraemer** [comment]
> I get this error when trying to login:

Oops, didn't check that login worked after some refactoring.

> Btw why use ?login? It's a demo, so having a button would be perfectly acceptable…

I was playing around with that functionality and thought I was suitable for the use case. But sure, simpler if it's always visible. Now changed.
